=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_IsmaelFG/examen/EX02_20230214_IsmaelFerreras/paises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Declaracion de tipos -->

    <xs:simpleType name="tipoContinente">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Europa"/>
            <xs:enumeration value="America"/>
            <xs:enumeration value="Asia"/>
            <xs:enumeration value="África"/>
            <xs:enumeration value="Antártida"/>
            <xs:enumeration value="Oceanía"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Declaracion de elementos-->
    <xs:element name="geografia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="continentes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="continente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pais" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="tipoContinente"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
                <xs:element name="paises">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pais" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sistema" type="xs:string"/>
                                        <xs:element name="superficie" type="xs:int"/>
                                        <xs:element name="moneda" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="antigua" type="xs:string"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="idioma" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rio" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre"/>
                                        <xs:element name="pais" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_AlvaroCM/examenes/EX02_20230214_AlvaroCordero/paises.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografia SYSTEM "paises.dtd">
<geografia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="paises.xsd">
    <continentes>
        <continente nombre="Europa">
            <pais>España</pais>
            <pais>Francia</pais>
            <pais>Suiza</pais>
        </continente>
        <continente nombre="America">
            <pais>Argentina</pais>
            <pais>Jamaica</pais>
            <pais>Uruguay</pais>
        </continente>
    </continentes>
    <paises>
        <pais nombre="España">
            <sistema>monarquía</sistema>
            <superficie>504645</superficie>
            <moneda>euro</moneda>
            <moneda antigua="antigua">peseta</moneda>
            <idioma>español</idioma>
        </pais>
        <pais nombre="Francia">
            <sistema>república</sistema>
            <superficie>675417</superficie>
            <moneda>euro</moneda>
            <moneda antigua="antigua">franco francés</moneda>
            <idioma>francés</idioma>
        </pais>
        <pais nombre="Suiza">
            <sistema>república</sistema>
            <superficie>41290</superficie>
            <moneda>franco suizo</moneda>
            <idioma>francés</idioma>
        </pais>
        <pais nombre="Uruguay">
            <sistema>república</sistema>
            <superficie>176215</superficie>
            <moneda>peso uruguayo</moneda>
            <idioma>español</idioma>
        </pais>
        <pais nombre="Argentina">
            <sistema>república</sistema>
            <superficie>2780400</superficie>
            <moneda>peso argentino</moneda>
            <idioma>español</idioma>
        </pais>
        <pais nombre="Jamaica">
            <sistema>monarquía</sistema>
            <superficie>10991</superficie>
            <moneda>dólar jamaicano</moneda>
            <idioma>inglés</idioma>
        </pais>
    </paises>
    <rios>
        <rio>
            <nombre>Uruguay</nombre>
            <pais>Argentina</pais>
            <pais>Uruguay</pais>
        </rio>
        <rio>
            <nombre>Ródano</nombre>
            <pais>Suiza</pais>
            <pais>Francia</pais>
        </rio>
        <rio>
            <nombre>Bidasoa</nombre>
            <pais>España</pais>
            <pais>Francia</pais>
        </rio>
    </rios>
</geografia>
