=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_IsmaelFG/ud4/11/11.dtd
<!ELEMENT catalogo (portatil*)>
<!ELEMENT portatil (referencia,nombre,fabricante,procesador,ram,disco+,pantalla+,grafica+,foto*)>
<!ELEMENT procesador (nombre,cache,numero,velocidad)>
<!ELEMENT ram (memoria,tipo)>
<!ELEMENT disco (capacidad)>
<!ELEMENT pantalla (dimension,resolucion,resolucionMax?)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fabricante EMPTY>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT capacidad (#PCDATA)>
<!ELEMENT dimension (#PCDATA)>
<!ELEMENT resolucion (#PCDATA)>
<!ELEMENT resolucionMax (#PCDATA)>
<!ELEMENT grafica (#PCDATA)>
<!ELEMENT foto (#PCDATA)> 
<!ATTLIST fabricante nombre (LENOVO|HP|APPLE|MSI|ASUS|DELL|DESCONOCIDO) #REQUIRED>
<!ATTLIST cache tamanyo (GB|MB|TB) "GB">
<!ATTLIST velocidad medida CDATA #FIXED "Ghz">
<!ATTLIST memoria unidadMedida (GB|MB|TB) "GB">
<!ATTLIST disco tipoDisco (SSD|HDD) #REQUIRED>
<!ATTLIST capacidad unidadMedidaDisco CDATA #REQUIRED>
<!ATTLIST dimension tamanyoPantalla CDATA #REQUIRED>
<!ATTLIST catalogo xmlns:xsi CDATA #IMPLIED
xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_IsmaelFG/ud4/11/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "11.dtd">

<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="11.xsd">
    <portatil>
        <referencia>AJ87898</referencia>
        <nombre>15-DA0204NS</nombre>
        <fabricante nombre="HP"/>
        <procesador>
            <nombre>I3-7020U</nombre>
            <cache tamanyo="GB">2</cache>
            <numero>1</numero>
            <velocidad medida="Ghz">2.3</velocidad>
        </procesador>
        <ram>
            <memoria unidadMedida="GB">8</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco tipoDisco="SSD">
            <capacidad unidadMedidaDisco="GB">256</capacidad>
        </disco>
        <pantalla>
            <dimension tamanyoPantalla="pulgadas">15</dimension>
            <resolucion>1366x768</resolucion>
            <resolucionMax>1980x1080</resolucionMax>
        </pantalla>
        <grafica>
            Integrada
        </grafica>
        <foto>
            portatil1.png
        </foto>
    </portatil>
    <portatil>
        <referencia>DK65208</referencia>
        <nombre>IDEAPAD S145</nombre>
        <fabricante nombre="LENOVO"/>
        <procesador>
            <nombre>I3-8145U</nombre>
            <cache tamanyo="GB">1</cache>
            <numero>1</numero>
            <velocidad medida="Ghz">2.1</velocidad>
        </procesador>
        <ram>
            <memoria unidadMedida="GB">8</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco tipoDisco="SSD">
            <capacidad unidadMedidaDisco="GB">256</capacidad>
        </disco>
        <pantalla>
            <dimension tamanyoPantalla="pulgadas">14</dimension>
            <resolucion>1980x1080</resolucion>
            <resolucionMax>1980x1080</resolucionMax>
        </pantalla>
        <grafica>
            Integrada
        </grafica>
        <foto>
            portatil2.png
        </foto>
    </portatil>
</catalogo>
