=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_AlvaroCM/_UD4/11/11.dtd
<!--ELEMENTOS-->
<!ELEMENT catalogo (portatil)*>
<!ELEMENT portatil (referencia,nombre,fabricante,procesador,ram,disco,pantalla,grafica,fotos*)>
<!ELEMENT procesador (nombre,cache,numeroProcesadores,velocidad)>
<!ELEMENT ram (memoria+,tipo+)>
<!ELEMENT disco (tipo,capacidad)>
<!ELEMENT pantalla (dimension,resolucion,resolucionMaxima?)>
<!ELEMENT fotos (nombreArchivo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fabricante EMPTY>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT numeroProcesadores (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT capacidad (#PCDATA)>
<!ELEMENT dimension (#PCDATA)>
<!ELEMENT resolucion (#PCDATA)>
<!ELEMENT resolucionMaxima (#PCDATA)>
<!ELEMENT grafica (#PCDATA)>
<!ELEMENT nombreArchivo (#PCDATA)>
<!--ATRIBUTOS-->
<!ATTLIST fabricante nombre (LENOVO|HP|APPLE|MSI|ASUS|DELL|DESCONOCIDO) #REQUIRED>
<!ATTLIST cache tamanyo (Gb|Mb|Tb) "Gb">
<!ATTLIST velocidad medida CDATA #FIXED "Ghz">
<!ATTLIST memoria unidadMedida (Gb|Mb|Tb) "Gb">
<!ATTLIST disco unidadMedidaDisco (Gb|Mb|Tb) "Gb">
<!ATTLIST capacidad unidadMedidaDisco CDATA #REQUIRED>
<!ATTLIST dimension tamanyoPantalla CDATA #REQUIRED>
<!ATTLIST catalogo xmlns:xsi CDATA #IMPLIED xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_AlexAS/ud4/11/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "11.dtd">
<catalogo>
    <portatil>
        <referencia>LN12345</referencia>
        <nombre>Portatil1</nombre>
        <!-- LENOVO HP APPLE MSI ASUS DELL DESCONOCIDO -->
        <fabricante nombre="HP"/>
        <procesador>
            <nombre>Intel core i3</nombre>
            <cache tamanyo="Gb">8</cache>
            <numero>2</numero>
            <velocidad medida="Ghz">3.5</velocidad>
        </procesador>
        <ram>
            <memoria unidadmedida="Gb">132</memoria>
            <!-- ddr3 ddr4 -->
            <tipomemoria>DDR3</tipomemoria>
        </ram>
        <disco tipo="SSD">
            <capacidad unidadmedidadisco="Gb">500</capacidad>
        </disco>
        <disco tipo="HDD">
            <capacidad unidadmedidadisco="Tb">1</capacidad>
        </disco>
        <pantalla>
            <dimension tamanyopantalla="pulgadas">15.6</dimension>
            <resolucion>1266x768</resolucion>
            <resolucionMaxima>1366x768</resolucionMaxima>
        </pantalla>
        <grafica>UHD Graphics 620</grafica>
        <fotos>foto1portatil1.png, foto2portatil1.png</fotos>
    </portatil>
</catalogo>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_CarlosGC/ud4/11/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE pedido SYSTEM "11.dtd">-->
<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="11.xsd"-->
<catalogo>
    <portatil>
        <referencia identificador="HP10219"/>
        <nombre>15-DA0204NS</nombre>
        <!-- Cadena de valores: LENOVO, HP, MSI, APPLE, ASUS, DELL, DESCONOCIDO.-->
        <fabricante nombre="Lenovo"></fabricante>
        <procesador>
            <nombre></nombre>
            <cache tamanyo="Gb"></cache>
            <numero>1</numero>
            <velocidad medida="Ghz">2.3</velocidad>
        </procesador>
        <ram>
            <memoria unidadMedida="Gb">8</memoria>
            <tipo>DDR4</tipo>
        </ram>
        <disco>
            <tipo>SSD</tipo>
            <almacenamiento unidadMedida="Gb">500</almacenamiento>
        </disco>
        <pantalla>
            <dimension>15.6_pulgadas</dimension>
            <resolucion>1266x768</resolucion>
            <!-- Esta es opcional.-->
            <resolucionMaxima>1366x768</resolucionMaxima>
        </pantalla>
        <grafica>Intel_UHD_Graphics_620</grafica>
        <foto>foto1.png</foto>
    </portatil>
</catalogo>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_OscarPF/ud4/11/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "11.dtd">
<catalogo>
    <portatil>
        <referencia>HP12345</referencia>
        <nombre>HP 15-DA0204NS</nombre>
        <fabricante nombre="HP"></fabricante> <!-- LENOVO|HP|MSI|APPLE|ASUS|DELL|DESCONOCIDO-->
        <procesador>
            <nombre>i3-7020U</nombre>
            <cache tamanyo="Gb">50</cache> <!-- Mb|Gb|Tb default Gb-->
            <numero>4</numero>
            <velocidad medida="Ghz">1.8</velocidad>
        </procesador>
        <ram>
            <memoria unidadMedida="Gb">8</memoria> <!-- Mb|Gb|Tb default Gb-->
            <tipoMemoria>DDR4</tipoMemoria> <!-- DDR3|DDR4-->
        </ram>
        <disco tipoDisco="SSD"> <!-- SSD|HDD-->
            <capacidad unidadMedidaDisco="Gb">256</capacidad> <!-- Mb|Gb|Tb default Gb-->
        </disco>
        <pantalla>
            <dimension tamanyoPantalla="pulgadas">15.6</dimension>
            <resolucion>1266x768</resolucion>
            <resolucionMaxima>1366x768</resolucionMaxima> <!-- OPCIONAL-->
        </pantalla>
        <grafica>3060ti</grafica>
        <foto>foto1.png</foto>
    </portatil>
</catalogo>
