=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_OscarP/ud4/10/10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Declaracion de tipos-->
    <xs:simpleType name="tipoPositivo">
        <xs:restriction base="xs:float">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoCantidad">
        <xs:restriction base="xs:string">
            <xs:pattern value="media|entera|2|6|12"/>
        </xs:restriction>
    </xs:simpleType>    
    <xs:simpleType name="tipoPlato">
        <xs:restriction base="xs:string">
            <xs:enumeration value="entrante"/>
            <xs:enumeration value="primero"/>
            <xs:enumeration value="segundo"/>
            <xs:enumeration value="postre"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="entrante"/>
            <xs:enumeration value="primero"/>
            <xs:enumeration value="segundo"/>
            <xs:enumeration value="postre"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Declaracion de elementos-->
    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plato" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="nombre">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="tipoCantidad">
                                            <xs:attribute name="tipo">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:pattern value="jamon|boletus|mixtas"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cantidad" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="tipoCantidad">
                                            <xs:attribute name="tipo">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:pattern value="unidades|racion"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sinGluten" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="opcion" type="xs:boolean"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minExclusive value="0"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="tipo" type="tipoPlato"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bebida" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre"/>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minExclusive value="0"/>
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>                    
                </xs:element>
                <xs:element name="formaPago">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="bizum" type="tipoPositivo"/>
                            <xs:element name="tarjeta" type="tipoPositivo"/>
                            <xs:element name="cripto" type="tipoPositivo"/>
                            <xs:element name="contado" type="tipoPositivo"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_CarlosGC/ud4/10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Entrantes, primeros, segundos, postres-->
<!-- Todos los nombres tiene un tamaÃ±o maximo de 100 caracteres y minimo de 4-->
<!-- Todos los nombres empiezan la primera letra con mayuscula-->

<!DOCTYPE pedido SYSTEM "10.dtd">
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="10.xsd">
    <plato tipo="entrante">
        <nombre tipo="jamon">Croquetas_de_Jamon_Caseras</nombre>
        <cantidad tipo="racionM">racionM</cantidad>
        <sinGluten opcion="true" />
        <precio>3.20</precio>
    </plato>
    <plato tipo="primero">
        <nombre>Macarrones_a_la_Carbonara</nombre>
        <precio>4.80</precio>
    </plato>
    <plato tipo="segundo">
        <nombre>Pollo_al_Ajillo</nombre>
        <precio>4.80</precio>
    </plato>
    <plato tipo="postre">
        <nombre>Coullant_de_Chocolate_Caliente_con_Nata</nombre>
        <precio>6</precio>
    </plato>
    <bebida>
        <nombre tipo="sin_gas" medida="ml" tamanyo="500">Agua</nombre>
        <precio>1.20</precio>
    </bebida>
    <bebida>
        <nombre tipo="sin_gas" medida="ml" tamanyo="1000">Agua</nombre>
        <precio>1.20</precio>
    </bebida>
    <bebida>
        <nombre tipo="con_gas" medida="ml" tamanyo="237">Fanta</nombre>
        <precio>1.20</precio>
    </bebida>
    <formaPago>
        <bizum>50</bizum>
    </formaPago>
</pedido>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_RebecaSP/ud4/10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE curriculum SYSTEM "10.dtd">-->
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="10.xsd">
    <!--entrante, primero, segundo y postre-->
    <!--todos los nombre tienen un tamaÃ±o maximo de 100 caracteres y min de 4-->
    <!--todos los platos empiezan por mayuscula-->
    <plato tipo="entrante">
        <nombre tipo="jamon">Croquetas caseras</nombre><!--jamon, boletus o mixtas-->
        <cantidad tipo="racion">media</cantidad>
        <sinGluten opcion="false"/>
        <precio>3.20</precio>
    </plato>
    <plato tipo="primero">
        <nombre>Macarrones a la carbonara</nombre>
        <sinGluten opcion="false"/>
        <precio>4.80</precio>
    </plato>
    <plato tipo="segundo">
        <nombre>Pollo al ajillo</nombre>
        <sinGluten opcion="true"/>
        <precio>4.80</precio>
    </plato>
    <plato tipo="postre">
        <nombre tipo="dulce">Coullant de chocolate caliente y nata</nombre>
        <precio>6</precio>
    </plato>
    <bebida>
        <nombre tipo="sin gas" medida="ml" tamanyo="500">Agua</nombre>
        <precio>1.20</precio>
    </bebida>
    <bebida>
        <nombre tipo="sin gas" medida="ml" tamanyo="1000">Agua</nombre>
        <precio>1.20</precio>
    </bebida>
    <bebida>
        <nombre tipo="con gas" medida="ml" tamanyo="250">Fanta</nombre>
        <precio>1.20</precio>
    </bebida>
    <formaPago><!--bizzum, visa, efectivo, criptomoneda-->
        <bizzum>50</bizzum>
    </formaPago>
</pedido>
