<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE horario [
	<!ELEMENT horario (dia+)>
	<!ELEMENT dia (nombredia, asignatura+)>
	<!ELEMENT nombredia (#PCDATA)>
	<!ELEMENT asignatura (nombreasignatura, horainicio, horafin)>
	<!ELEMENT nombreasignatura (#PCDATA)>
	<!ELEMENT horainicio (#PCDATA)>
	<!ELEMENT horafin (#PCDATA)>
]>
<horario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsd07.xsd">
	<dia>
		<nombredia>LUNES</nombredia>
		<asignatura>
			<nombreasignatura>EDD</nombreasignatura>
			<horainicio>08:30</horainicio>
			<horafin>09:20</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>FOL</nombreasignatura>
			<horainicio>09:20</horainicio>
			<horafin>10:10</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>10:10</horainicio>
			<horafin>11:00</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>RECREO</nombreasignatura>
			<horainicio>11:00</horainicio>
			<horafin>11:25</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>11:25</horainicio>
			<horafin>12:15</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>SINF</nombreasignatura>
			<horainicio>12:15</horainicio>
			<horafin>13:05</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>SINF</nombreasignatura>
			<horainicio>13:05</horainicio>
			<horafin>13:55</horafin>
		</asignatura>
	</dia>
	<dia>
		<nombredia>MARTES</nombredia>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>08:30</horainicio>
			<horafin>09:20</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>09:20</horainicio>
			<horafin>10:10</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>LMSGI</nombreasignatura>
			<horainicio>10:10</horainicio>
			<horafin>11:00</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>RECREO</nombreasignatura>
			<horainicio>11:00</horainicio>
			<horafin>11:25</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>LMSGI</nombreasignatura>
			<horainicio>11:25</horainicio>
			<horafin>12:15</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>BBDD</nombreasignatura>
			<horainicio>12:15</horainicio>
			<horafin>13:05</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>BBDD</nombreasignatura>
			<horainicio>13:05</horainicio>
			<horafin>13:55</horafin>
		</asignatura>
	</dia>
	<dia>
		<nombredia>MIERCOLES</nombredia>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>08:30</horainicio>
			<horafin>09:20</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>09:20</horainicio>
			<horafin>10:10</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>EDD</nombreasignatura>
			<horainicio>10:10</horainicio>
			<horafin>11:00</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>RECREO</nombreasignatura>
			<horainicio>11:00</horainicio>
			<horafin>11:25</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>FOL</nombreasignatura>
			<horainicio>11:25</horainicio>
			<horafin>12:15</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>BBDD</nombreasignatura>
			<horainicio>12:15</horainicio>
			<horafin>13:05</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>BBDD</nombreasignatura>
			<horainicio>13:05</horainicio>
			<horafin>13:55</horafin>
		</asignatura>
	</dia>
	<dia>
		<nombredia>JUEVES</nombredia>
		<asignatura>
			<nombreasignatura>SINF</nombreasignatura>
			<horainicio>08:30</horainicio>
			<horafin>09:20</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>SINF</nombreasignatura>
			<horainicio>09:20</horainicio>
			<horafin>10:10</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>10:10</horainicio>
			<horafin>11:00</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>RECREO</nombreasignatura>
			<horainicio>11:00</horainicio>
			<horafin>11:25</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>PROG</nombreasignatura>
			<horainicio>11:25</horainicio>
			<horafin>12:15</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>LMSGI</nombreasignatura>
			<horainicio>12:15</horainicio>
			<horafin>13:05</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>LMSGI</nombreasignatura>
			<horainicio>13:05</horainicio>
			<horafin>13:55</horafin>
		</asignatura>
	</dia>
	<dia>
		<nombredia>VIERNES</nombredia>
		<asignatura>
			<nombreasignatura>EDD</nombreasignatura>
			<horainicio>08:30</horainicio>
			<horafin>09:20</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>BBDD</nombreasignatura>
			<horainicio>09:20</horainicio>
			<horafin>10:10</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>BBDD</nombreasignatura>
			<horainicio>10:10</horainicio>
			<horafin>11:00</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>RECREO</nombreasignatura>
			<horainicio>11:00</horainicio>
			<horafin>11:25</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>FOL</nombreasignatura>
			<horainicio>11:25</horainicio>
			<horafin>12:15</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>SINF</nombreasignatura>
			<horainicio>12:15</horainicio>
			<horafin>13:05</horafin>
		</asignatura>
		<asignatura>
			<nombreasignatura>SINF</nombreasignatura>
			<horainicio>13:05</horainicio>
			<horafin>13:55</horafin>
		</asignatura>
	</dia>
</horario>