=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_ErikaMP/ud4/11/11.dtd
<!ELEMENT catalogo (portatil*)>
<!ELEMENT portatil (referencia,nombre,fabricante,procesador,ram,disco+,pantalla+,grafica+,foto)>
<!ELEMENT procesador (nombre,cache,numero,velocidad)>
<!ELEMENT ram (memoria,tipo)>
<!ELEMENT disco (capacidad)>
<!ELEMENT pantalla (dimension,resolucion,resolucionmax?)>

<!ELEMENT referencia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fabricante EMPTY>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT capacidad (#PCDATA)>
<!ELEMENT dimension (#PCDATA)>
<!ELEMENT resolucion (#PCDATA)>
<!ELEMENT resolucionmax (#PCDATA)>
<!ELEMENT grafica (#PCDATA)>
<!ELEMENT foto (#PCDATA)>

<!ATTLIST fabricante nombre (lenovo|hp|msi|apple|asus|dell|desconocido) #REQUIRED>
<!ATTLIST cache tamanyo (Mg|Gb|Tb) "Gb">
<!ATTLIST velocidad medida CDATA #FIXED "Ghz">
<!ATTLIST memoria unidad_medida (Mg|Gb|Tb) "Gb">
<!ATTLIST disco tipo (SSD|HDD) #REQUIRED>
<!ATTLIST capacidad unidad_medida (Mg|Gb|Tb) "Gb">
<!ATTLIST dimension tamanyo CDATA #FIXED "pulgadas">

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_ErikaMP/ud4/11/11.xml
<!DOCTYPE catalogo SYSTEM "11.dtd">
<catalogo> <!-- de 0 o de más portatiles-->
    <portatil>
        <referencia></referencia> <!-- ID con 2 letras y 5 digitos númericos-->
        <nombre></nombre> <!-- cadena caracteres maximo 20 caracteres -->
        <fabricante nombre="lenovo"/> <!-- lenovo,hp,msi,apple,asus,dell,desconocido -->
        <procesador>
            <nombre></nombre> <!-- no restriccion -->
            <cache tamanyo="Gb"></cache> <!-- tamanyo: mg,gb,tb - por defecto: gb / cache: float -->
            <numero></numero> <!-- numero: integer, min:1 - max:20 -->
            <velocidad medida="Ghz"></velocidad> <!-- medida: float / valor fijo medida: Ghz -->
        </procesador> 
        <ram>
            <memoria unidad_medida="Gb"></memoria> <!-- memoria: integer / unidad_medida: mg,gb,tb - por defecto: gb dos caracteres -->
            <tipo></tipo> <!-- tipo de valores string DDR3 - DDR4 -->
        </ram>
        <disco tipo="SSD"> <!-- tipo: SSD o HDD -->
            <capacidad unidad_medida="Gb"></capacidad> <!-- memoria: integer / unidad_medida: mg,gb,tb - por defecto: gb dos caracteres -->
        </disco> 
        <pantalla>
            <dimension tamanyo="pulgadas"></dimension> <!-- dimension: float - fragmentDigits:1 -->
            <resolucion></resolucion>
            <resolucionmax></resolucionmax> <!-- opcional -->
        </pantalla>
        <grafica></grafica> <!-- cadena -->
        <foto></foto><!-- de 0 o de más fotos de portatiles-->
    </portatil>
</catalogo>
