=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_ErikaMP/exams/20230321_EX03_ErikaMartínez/01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productosfinancieros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="bono">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="valoractual">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:restriction base="xs:float"/>
                                                </xs:simpleContent>
                                                <xs:attribute name="moneda">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="yenes"/>
                                                            <xs:enumeration value="dolares"/>
                                                            <xs:enumeration value="euros"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="beneficio" type="xs:float"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="futuro">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="elemento">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:restriction base="xs:string"/>
                                                </xs:simpleContent>
                                                <xs:attribute name="idioma" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="beneficio" type="xs:float"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="acciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="empresa">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:restriction base="xs:string"/>
                                                </xs:simpleContent>
                                                <xs:attribute name="pais" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="beneficio" type="xs:float"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_RebecaSP/examenes/03/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<productosfinancieros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <producto> <!--UNO O MAS-->
        <bono> <!--PUEDE SER BONO, FUTURO O ACCIONES-->
            <valoractual moneda="yenes">2.212</valoractual> <!--MONEDA DOLARES, EUROS O YENES-->
            <beneficio>-2.83</beneficio> <!--OBLIGATORIO DECIMAL POSITIVO O NEGATIVO-->
        </bono>
    </producto>
    <producto>
        <futuro>
            <elemento idioma="espanol">Petroleo</elemento>
            <beneficio>-3.83</beneficio>
        </futuro>
    </producto>
    <producto>
        <acciones>
            <empresa pais="usa">ENRON</empresa> <!--pais: usa, alemania, japon y espana-->
            <beneficio>2.91</beneficio>
        </acciones>
    </producto>
</productosfinancieros>
