=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_CarlosGC/ud4/01/01.dtd
<!ELEMENT mail (remitente, destinatario+, fecha, asunto?, mensaje?, image*)>
<!ELEMENT fecha (anyo,mes,dia)>
<!ELEMENT image (nombre,tipo)>
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ATTLIST mail xmlns:xsi CDATA #IMPLIED
                xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_RebecaSP/ud4/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mail SYSTEM "01.dtd">
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>
        pepe@gmail.com
    </remitente>
    <destinatario>
        gaza@gmail.com
    </destinatario>
    <destinatario>
        lauki@gmail.com
    </destinatario>
    <fecha>
        <dia>---17</dia>
        <mes>--01</mes>
        <anyo>2023</anyo>
    </fecha>
    <asunto>Los Quintos de CostroGonzalo 2023</asunto>
    <mensaje><![CDATA[
        Lista de la compra:
        1. Cocacola
        2. Kas naranja
        3. Bitterkas
        4. Acuarius
        ]]>
    </mensaje>
    <image>
        <nombre>Foto</nombre>
        <tipo>png</tipo>
    </image>
</mail>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_BorjaNR/ud4/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    author: Borja
    date: 17/01/2023
    description: XML01
-->

<!DOCTYPE mail SYSTEM "01.dtd">

<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>
        pepe@gmail.com
    </remitente>
    <destinatario>
        gaz@gmail.com
    </destinatario>
    <destinatario>
        lauki@gamil.com
    </destinatario>
    <destinatario>
        cobreros@gmail.com
    </destinatario>
    <fecha>
        <dia>---17</dia>
        <mes>--01</mes>
        <anyo>2023</anyo>
    </fecha>
    <asunto>Los Quintos de Castrogonzalo 2023</asunto>
    <mensaje><![CDATA[ 
        1. Red Label
        2. Barcelo
        3. Seagram
        4. Cerveza
        5. Vino
        6. Agua
    ]]></mensaje>
    <image>
        <nombre>ismael1.jpg</nombre>
        <tipo>image/jpg</tipo>
    </image>
    <image>
        <nombre>ismael1.png</nombre>
        <tipo>image/png</tipo>
    </image>
</mail>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_AlexAS/ud4/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    author: Alex
    date: 17/01/2023
    description: Escribir un documento XML que almacene la informacion de un mail y contenga la siguiente
    informacion: remitente, destinatario(s), fecha del mensaje, asunto, mensaje, ficheros adjuntos (por cada fichero debe
    especificar el nombre y el tipo MIME). No utilizar atributos
-->
<!DOCTYPE mail SYSTEM "01.dtd">
<mail>
    <remitente>
        pepe@gmail.com
    </remitente>
    <destinatario>
        gaza@gmail.com
    </destinatario>

    <destinatario>
        lauki@gmail.com
    </destinatario>

    <destinatario>
        cobreros@gmail.com
    </destinatario>

    <fecha>
        <dia>17</dia>
        <mes>1</mes>
        <anyo>2023</anyo>
    </fecha>
    <asunto>Los Quintos de Castro Gonzalo 2023</asunto>
    <mensaje><![CDATA[ 
        1. Coca cola
        2.Kas naranja
        3. Kas limon
        4. Tonica
        5. Agua
        ]]></mensaje>
    <image>
        <nombre>ismael1.jpg</nombre>
        <tipo>image/jpeg</tipo> 
    </image>
    <image>
        <nombre>borja1.png</nombre>
        <tipo>image/png</tipo> 
    </image>
</mail>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_CarlosGC/ud4/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Author: Carlos Garcia Cachon
    Date: 17/01/2023
    Description: Escribir un documento XML que almacene la información de un mail y contenga la siguiente información: remitente, 
                destinatario(s), fecha del mensaje, asunto, mensaje, ficheros adjuntos (por cada fichero debe especificar el nombre y el tipo 
                MIME). No utilizar atributos
-->

<!DOCTYPE mail SYSTEM "01.dtd">
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>
        pepe@gmail.com
    </remitente>
    <destinatario>
        gaza@gmail.com
    </destinatario>
    <destinatario>
        cobreros@gmail.com
    </destinatario>
    <destinatario>
        entrepinares@gmail.com
    </destinatario>
    <fecha>
        <anyo>2023</anyo>
        <mes>01</mes>
        <dia>17</dia>
    </fecha>
    <asunto>Los Quintos de Castrogonzalo 2023</asunto>
    <mensaje><![CDATA[
        1. Red Label
        2. Black Label
        3. Four Roses
        4. Ballantines
        5. Jack Daniels]]></mensaje>
    <image>
        <nombre>Ismael1.jpeg</nombre>
        <tipo>image/jpeg</tipo>
    </image>
    <image>
        <nombre>Borja1.png</nombre>
        <tipo>image/png</tipo>
    </image>
</mail>
