=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_ErikaMP/ud4/05/05.dtd
<!-- 
    Autor: Erika Martínez Pérez
    Práctica: Actividad 5
    Descripción: Conversión del ejercicio 05 a DTD
-->
<!ELEMENT Company (Employee+)>
<!ELEMENT Employee (Firtsname,Lastname,ContactNo+,Email,Address)>
<!ELEMENT Address (City,State,Zip)>

<!ELEMENT Firtsname (#PCDATA)>
<!ELEMENT Lastname (#PCDATA)>
<!ELEMENT ContactNo (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_AlexAS/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    author: Alex
    date: 19/01/2023
    description: Representar en un documento XML con los siguientes datos

-->
<!DOCTYPE Company SYSTEM "05.dtd">
<Company>
    <Employee>
        <FirstName>Juan</FirstName>
        <LastName>Sanchez</LastName>
        <ContactNo>123456789</ContactNo>
        <Email>juansanchez@company.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>
            </Address>
    </Employee>
</Company>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_OscarPF/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Company SYSTEM "05.dtd">
<Company>
    <Employee>
        <FirstName></FirstName>
        <LastName></LastName>
        <ContactNo></ContactNo>
        <Email></Email>
        <Address>
            <City></City>
            <State></State>
            <Zip></Zip>
        </Address>
    </Employee>
</Company>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_IsmaelFG/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Company SYSTEM "05.dtd">
<!--
Descripción:
Autor: Ismael Ferreras García
Fecha creación/modificación: 17/01/2023
-->
<Company>
	<Employee>
		<FirstName>
			Sanchez
		</FirstName>
		<LastName>
			Juan
		</LastName>
		<ContactNo>
			123456789
		</ContactNo>
		<Email>
			juansanchez@company.com
		</Email>
		<Address>
			<City>
				Bangalore
			</City>
			<State>
				Karnataka
			</State>
			<Zip>
				560212
			</Zip>
		</Address>
	</Employee>
</Company>

=== SaucesMarcas/2223_LMSGI_Alumnos/portfolio/2223_lmsgi_ErikaMP/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Autor: Erika Martínez Pérez
    Práctica: Actividad 5
    Descripción: Escribir un documento XML que represente la estructura y almacene la siguiente información: Juan Sanchez, telefono de contacto 
                123456789 con email juansanchez@company.com que vive en Bangalore, estado Karnataka con código 560212
-->
<!DOCTYPE Company SYSTEM "05.dtd">
<Company>
    <Employee>
        <Firtsname>Juan</Firtsname>
        <Lastname>Sanches</Lastname>
        <ContactNo>123456789</ContactNo>
        <Email>juansanchez@company.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>
        </Address>
    </Employee>
</Company>
